version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306

    environment:
      - LANG=C.UTF-8
      - TERM=dumb
      - MYSQL_ROOT_PASSWORD=thoughtworks
      - MYSQL_DATABASE=mahong
      - MYSQL_PASSWORD=mahong
      - MYSQL_USER=mahong
    networks:
      main:
        aliases:
          - mysql
  back_end:
    image: jetty:9.3
    volumes:
      - ./back_end/build/libs:/var/lib/jetty/webapps
    ports:
      - "8080:8080"
    networks:
      main:
        aliases:
          - back_end
  bff:
    image: node:6.9.5
    ports:
      - "3000:3000"
    volumes:
      - ./bff:/var/app
    command: bash -c "cd /var/app && node app.js"
    networks:
      main:
        aliases:
          - bff
  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
    networks:
      main:
        aliases:
          - mongo
  jenkins-dind:
    image: jenkins:latest
    ports:
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      main:
        aliases:
          - jenkins
  nginx:
    image: nginx:1.9
    ports:
      - "8888:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./web/public/assets:/var/twars/web
    networks:
      main:
        aliases:
          - nginx

networks:
  main:

